.PHONY: test

test:
	node /home/james/workspace/rustWasmSample/node_modules/mocha/bin/mocha.js --require ts-node/register --extension ts --loader=ts-node/esm --ui bdd --reporter /home/james/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/223.8214.51/plugins/nodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js
